services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fraude_user
      POSTGRES_PASSWORD: fraude_pass
      POSTGRES_DB: fraude_back
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraude_user -d fraude_back"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      APP_NAME: fraude-back
      APP_ENV: development
      API_V1_STR: /api/v1
      SQLALCHEMY_ECHO: "false"
      DATABASE_URL: postgresql+psycopg2://fraude_user:fraude_pass@db:5432/fraude_back
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini:ro
      - ./storage:/app/storage
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
